<?php
// Automatically Generated by TestLink Installer - Wed, 22 Jan 25 21:11:08 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'admin');
define('DB_PASS', 'admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink-task');
define('DB_TABLE_PREFIX', '');
